# Generated by Django 2.2.4 on 2019-08-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_EMPLOYEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('header_image', models.ImageField(null=True, upload_to='images', verbose_name='头像')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'TB_EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='TB_USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_ID', models.CharField(max_length=64, verbose_name='微信唯一标识')),
                ('username', models.CharField(max_length=32, verbose_name='用户微信名称')),
                ('user_image', models.ImageField(null=True, upload_to='images', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'TB_USER',
            },
        ),
        migrations.CreateModel(
            name='TB_COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='评论内容')),
                ('score', models.IntegerField(default=1, verbose_name='评分')),
                ('add_time', models.DateField(auto_now=True, verbose_name='评论时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeName', to='api.TB_EMPLOYEE', verbose_name='员工')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userName', to='api.TB_USER', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'TB_COMMENT',
            },
        ),
    ]
