# Generated by Django 2.2.5 on 2019-09-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '会员', 'verbose_name_plural': '会员'},
        ),
    ]
